# Author:     Thomas D'haenens
# Created:    14/09/2019 8:21
# License:    GPLv3


# IMPORT: Standard Modules
from importlib.util import spec_from_file_location, module_from_spec                            # Module Loader Lib
from alembic.config import Config                                                               # Alembic Config Function
from alembic import command                                                                     # Alembic Command Lib

# IMPORT: Custom Modules
from basic import *                                                                             # Basic Lib


# FUNCTION: Prohibit Deletion Revisions
def prohibitDeletionRevisions(path):
    currentContent = readTextFile(path)
    currentContent = currentContent.split('\n')
    newContent = ''
    for i,line in enumerate(currentContent):
        if ('op.drop_table' not in line) and ('op.drop_column' not in line):
            newContent += line + '\n'
        else:
            appLogger.debug('Dropping Alembic revision line: ' + str(line))
    currentContent = newContent.split('\n')
    newContent = ''
    for i,line in enumerate(currentContent):
        if ('commands auto generated by Alembic' in line) and (i < len(currentContent)-1) and ('end Alembic commands' in currentContent[i+1]):
            newContent += line + '\n'
            newContent += '    pass' + '\n'
        else:
            newContent += line + '\n'
    writeTextFile(path, newContent)


# CONFIGURATION: Determine Installation Location
locationConfig = readJSONFile('/etc/neatly/base/location.json')

# CONFIGURATION: Determine DB Properties
dbConfig = readJSONFile('/etc/neatly/base/db.json')


# IMPORT: Custom Modules
spec = spec_from_file_location('tables', locationConfig['lib'] + 'tables.py')                   # Import Tables
tables = module_from_spec(spec)                                                                 # Import Tables
spec.loader.exec_module(tables)                                                                 # Import Tables


# CONFIGURATION: Define Alembic Configuration
config = Config()
config.set_main_option('script_location', 'migrations')
config.set_main_option('sqlalchemy.url', createDBPathConfig(dbConfig['connection']))


# CREATE: Create Automatic Migration Script for DB
revision = command.revision(config, '.'.join([dbConfig['connection']['ip'], dbConfig['connection']['type'], dbConfig['connection']['db']]), True, False, 'head', False, None, None, None, None, None)


# Prohibit Deletions Revisions
prohibitDeletionRevisions(revision.path)

# Perform Change Operations to DB
appLogger.info('Performing database migration from tag ' + str(revision.down_revision) + ' to tag ' + str(revision.revision))
command.upgrade(config, 'head')
